// strings.js — every player-visible string (localisation = swap this file).
export const STR = {
  title: 'MOTO RUSH X3',
  tagline: 'Send it. Flip it. Beat the clock.',
  loading: 'LOADING…',
  tapToStart: 'Tap / Click / Press to start',
  play: 'PLAY',
  levelSelect: 'SELECT LEVEL',
  best: 'BEST',
  noTime: '—',
  locked: 'LOCKED',
  clearPrev: 'Clear the level before to unlock',
  level: 'LEVEL',
  checkpoint: 'CHECKPOINT!',
  flip: 'FLIP!',
  flip2: 'DOUBLE FLIP!',
  flip3: 'TRIPLE FLIP!',
  flipN: 'FLIP x',
  bonus: '-0.5s',
  crash: 'CRASHED!',
  tapRetry: 'Tap to respawn',
  levelComplete: 'LEVEL COMPLETE',
  yourTime: 'TIME',
  flipsSaved: 'FLIP BONUS',
  newRecord: 'NEW RECORD!',
  retry: 'RETRY',
  next: 'NEXT',
  menu: 'MENU',
  paused: 'PAUSED',
  resume: 'RESUME',
  // control hints
  hintKeys: '▲ gas   ▼ brake   ◀ lean back / backflip   ▶ lean forward / frontflip',
  hintTouch: 'Left buttons lean · right buttons gas & brake · lean back to land flips',
  gas: 'GAS', brake: 'BRAKE', leanL: '↺', leanR: '↻',
  sound: 'SOUND',
  // v1.1 additions
  settings: 'SETTINGS', music: 'MUSIC', sfx: 'SFX', motion: 'REDUCED MOTION',
  haptics: 'VIBRATION', muteAll: 'MUTE ALL', on: 'ON', off: 'OFF', close: 'CLOSE',
  install: 'INSTALL', score: 'SCORE', bigAir: 'BIG AIR!', nearMiss: 'NEAR MISS!',
  bestScore: 'BEST',
};
